[1m============================= test session starts ==============================[0m
platform linux -- Python 3.10.12, pytest-6.2.5, py-1.10.0, pluggy-0.13.0
cachedir: /home/stajyer-pc/UAV-Assessment-Template/assessment_ws/build/test_package/.pytest_cache
rootdir: /home/stajyer-pc/UAV-Assessment-Template/assessment_ws/src/test_package
plugins: launch-testing-ros-0.19.9, launch-testing-1.0.9, ament-pep257-0.12.12, ament-flake8-0.12.12, ament-xmllint-0.12.12, ament-copyright-0.12.12, ament-lint-0.12.12, colcon-core-0.19.0, cov-3.0.0
[1mcollecting ... [0m[1m
collecting 0 items / 1 error                                                   [0m[1m
collected 0 items / 1 error                                                    [0m

==================================== ERRORS ====================================
[31m[1m________________________ ERROR collecting test session _________________________[0m
[1m[31m/usr/lib/python3/dist-packages/pluggy/hooks.py[0m:286: in __call__
    [94mreturn[39;49;00m [96mself[39;49;00m._hookexec([96mself[39;49;00m, [96mself[39;49;00m.get_hookimpls(), kwargs)
[1m[31m/usr/lib/python3/dist-packages/pluggy/manager.py[0m:92: in _hookexec
    [94mreturn[39;49;00m [96mself[39;49;00m._inner_hookexec(hook, methods, kwargs)
[1m[31m/usr/lib/python3/dist-packages/pluggy/manager.py[0m:83: in <lambda>
    [96mself[39;49;00m._inner_hookexec = [94mlambda[39;49;00m hook, methods, kwargs: hook.multicall(
[1m[31m/usr/lib/python3/dist-packages/_pytest/python.py[0m:200: in pytest_collect_file
    module: Module = ihook.pytest_pycollect_makemodule(path=path, parent=parent)
[1m[31m/usr/lib/python3/dist-packages/pluggy/hooks.py[0m:286: in __call__
    [94mreturn[39;49;00m [96mself[39;49;00m._hookexec([96mself[39;49;00m, [96mself[39;49;00m.get_hookimpls(), kwargs)
[1m[31m/usr/lib/python3/dist-packages/pluggy/manager.py[0m:92: in _hookexec
    [94mreturn[39;49;00m [96mself[39;49;00m._inner_hookexec(hook, methods, kwargs)
[1m[31m/usr/lib/python3/dist-packages/pluggy/manager.py[0m:83: in <lambda>
    [96mself[39;49;00m._inner_hookexec = [94mlambda[39;49;00m hook, methods, kwargs: hook.multicall(
[1m[31m/opt/ros/humble/lib/python3.10/site-packages/launch_testing/pytest/hooks.py[0m:193: in pytest_pycollect_makemodule
    entrypoint = find_launch_test_entrypoint(path)
[1m[31m/opt/ros/humble/lib/python3.10/site-packages/launch_testing/pytest/hooks.py[0m:186: in find_launch_test_entrypoint
    module = path.pyimport()
[1m[31m/usr/lib/python3/dist-packages/py/_path/local.py[0m:704: in pyimport
    [96m__import__[39;49;00m(modname)
[1m[31m<frozen importlib._bootstrap>[0m:1027: in _find_and_load
    [04m[91m?[39;49;00m[04m[91m?[39;49;00m[04m[91m?[39;49;00m
[1m[31m<frozen importlib._bootstrap>[0m:1006: in _find_and_load_unlocked
    [04m[91m?[39;49;00m[04m[91m?[39;49;00m[04m[91m?[39;49;00m
[1m[31m<frozen importlib._bootstrap>[0m:688: in _load_unlocked
    [04m[91m?[39;49;00m[04m[91m?[39;49;00m[04m[91m?[39;49;00m
[1m[31m/usr/lib/python3/dist-packages/_pytest/assertion/rewrite.py[0m:170: in exec_module
    exec(co, module.[91m__dict__[39;49;00m)
[1m[31mtest/test_task_1_arm_disarm.py[0m:18: in <module>
    [37m@launch_testing[39;49;00m.markers.keep_alive
[1m[31mE   AttributeError: module 'launch_testing' has no attribute 'markers'[0m
- generated xml file: /home/stajyer-pc/UAV-Assessment-Template/assessment_ws/build/test_package/pytest.xml -
=========================== short test summary info ============================
ERROR  - AttributeError: module 'launch_testing' has no attribute 'markers'
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
[31m=============================== [31m[1m1 error[0m[31m in 0.75s[0m[31m ===============================[0m
